"""Dataset loading with explicit provenance: real books, real prices (+ modelled books), synthetic.

Every dataset carries a :class:`DatasetInfo` whose banner is printed at the top of every
notebook and stamped on every figure, so a reader can never mistake simulated data for
market data:

* ``real_books``  - live WebSocket order books recorded by ``src.recorder`` (executable);
* ``real_prices`` - Polymarket ``/prices-history`` (real prices, but NOT executable: books
  used for execution are *modelled* around them and labelled as such);
* ``synthetic``   - seeded generator output, only ever a labelled fallback.

``BAYES_DATA_MODE`` (``auto`` | ``real`` | ``real_books`` | ``real_prices`` | ``synthetic``)
overrides the preference order; ``real`` never falls back to synthetic data.
"""
from __future__ import annotations

import json
import logging
import math
import os
from dataclasses import asdict, dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Iterator, Sequence

import numpy as np
import pandas as pd

from . import HIST_ROOT, PRICES_ROOT, code_version
from .config import Basket, MarketsConfig, get_basket, load_markets
from .events import BookEvent, Event, MetaEvent, MarketResolvedEvent, px_to_int

logger = logging.getLogger(__name__)


class DataKind(str, Enum):
    REAL_BOOKS = "real_books"
    REAL_PRICES = "real_prices"
    SYNTHETIC = "synthetic"


class DataUnavailable(RuntimeError):
    """The requested data kind does not exist for this basket."""


BANNERS = {
    DataKind.REAL_BOOKS: "**DATA: REAL Polymarket order books** recorded live from the CLOB market WebSocket.",
    DataKind.REAL_PRICES: ("**DATA: REAL Polymarket price history** (`/prices-history`). Prices are real but not "
                           "executable; wherever execution is simulated, bid/ask/depth are **MODELLED** around them."),
    DataKind.SYNTHETIC: ("**⚠ SYNTHETIC DATA — NOT REAL MARKET DATA.** Generated by `src/synthetic.py` (seeded). "
                         "Results demonstrate the method only; any mean reversion is implied by the generator by "
                         "construction."),
}


@dataclass
class DatasetInfo:
    kind: DataKind
    basket_id: str
    title: str
    t_start: str | None = None
    t_end: str | None = None
    hours: float = 0.0
    n_rows: int = 0
    n_sessions: int = 0
    sources: list[dict] = field(default_factory=list)
    seed: int | None = None
    notes: list[str] = field(default_factory=list)

    @property
    def synthetic(self) -> bool:
        return self.kind == DataKind.SYNTHETIC

    @property
    def label(self) -> str:
        """``data_kind`` string understood by ``src.plotting``."""
        return self.kind.value

    def banner_markdown(self) -> str:
        lines = [BANNERS[self.kind], "",
                 "| basket | from | to | hours | rows | sessions |", "|---|---|---|---|---|---|",
                 f"| `{self.basket_id}` ({self.title}) | {self.t_start} | {self.t_end} | {self.hours:.1f} | "
                 f"{self.n_rows:,} | {self.n_sessions} |"]
        if self.seed is not None:
            lines.append(f"\nSynthetic seed: `{self.seed}`")
        for n in self.notes:
            lines.append(f"\n> {n}")
        return "\n".join(lines)

    def to_json(self) -> dict:
        d = asdict(self)
        d["kind"] = self.kind.value
        d["synthetic"] = self.synthetic
        d["code_version"] = code_version()
        return d


def _iso(t_ns: float | int | None) -> str | None:
    if t_ns is None or not math.isfinite(float(t_ns)):
        return None
    return pd.Timestamp(int(t_ns), unit="ns", tz="UTC").isoformat(timespec="seconds")


@dataclass
class Dataset:
    info: DatasetInfo
    basket: Basket
    _frames: Callable[[], Iterator[tuple[int, list[Event]]]]
    _tob: Callable[[], pd.DataFrame]

    def frames(self) -> Iterator[tuple[int, list[Event]]]:
        """Re-iterable ``(t_recv_ns, events)`` stream for the backtest pipeline."""
        return self._frames()

    def top_of_book(self) -> pd.DataFrame:
        """Long table in the shared ``TOB_COLUMNS`` schema (``leg`` = leg_id)."""
        return self._tob()


# --------------------------------------------------------------------------- real books
def recorded_groups(basket_id: str, root: Path = HIST_ROOT) -> list[str]:
    out = []
    for man in sorted(Path(root).glob("*/manifest.json")):
        with open(man, encoding="utf-8") as fh:
            m = json.load(fh)
        if not m.get("synthetic") and any(basket_id in (s.get("baskets") or {}) for s in m.get("sessions", [])):
            out.append(man.parent.name)
    return out


def load_real_books(basket_id: str, *, group: str | None = None, root: Path = HIST_ROOT,
                    cfg: MarketsConfig | None = None, min_hours: float = 0.0) -> Dataset:
    from .recorder import export_tob, list_sessions, read_tob_csv, replay_frames, status

    cfg = cfg or load_markets()
    basket = get_basket(basket_id, cfg)
    groups = [group] if group else recorded_groups(basket_id, root)
    if not groups:
        raise DataUnavailable(f"no recordings for {basket_id} under {root}")
    g = groups[0]
    st = status(g, root)
    sessions = [s for s in list_sessions(g, root) if basket_id in (s.get("baskets") or {})]
    if not sessions or st["hours_recorded"] < min_hours:
        raise DataUnavailable(f"{basket_id}: {st['hours_recorded']:.2f} h recorded < {min_hours} h")
    tob_path = Path(root) / g / "tob" / f"{basket_id}.csv.gz"
    man_path = Path(root) / g / "manifest.json"
    if not tob_path.exists() or tob_path.stat().st_mtime < man_path.stat().st_mtime:
        export_tob(g, [basket_id], root=root, cfg=cfg)
    tob = read_tob_csv(tob_path)
    hours = sum((pd.Timestamp(s["ended"]) - pd.Timestamp(s["started"])).total_seconds() / 3600
                for s in sessions if s.get("ended"))
    info = DatasetInfo(DataKind.REAL_BOOKS, basket_id, basket.title, sessions[0]["started"][:19],
                       (sessions[-1].get("ended") or sessions[-1]["started"])[:19], hours, len(tob), len(sessions),
                       [{"group": g, "manifest": str(Path(root) / g / "manifest.json")}])
    if hours < 24:
        info.notes.append(f"Only {hours:.1f} h of live books so far (recording continues in ≤2 h chunks); "
                          "treat backtest statistics on this sample as anecdotal.")

    def frames() -> Iterator[tuple[int, list[Event]]]:
        return replay_frames(g, root=root)

    return Dataset(info, basket, frames, lambda: tob)


# --------------------------------------------------------------------------- real prices
def load_prices_long(basket_id: str, root: Path = PRICES_ROOT) -> pd.DataFrame:
    from .recorder import load_prices_history

    p = Path(root) / basket_id / "manifest.json"
    if not p.exists():
        raise DataUnavailable(f"no price history for {basket_id}; run python -m src.recorder backfill --basket {basket_id}")
    return load_prices_history(basket_id, root)


def prices_grid(basket_id: str, *, fidelity_s: int = 60, root: Path = PRICES_ROOT,
                cfg: MarketsConfig | None = None, max_gap: str = "15min") -> pd.DataFrame:
    """Wide 1-minute (or hourly) grid of leg prices; columns ordered as basket legs.

    LOCF only within ``max_gap`` (never interpolated); rows where any leg is missing are
    dropped, so every row is a complete basket observation.
    """
    cfg = cfg or load_markets()
    basket = get_basket(basket_id, cfg)
    df = load_prices_long(basket_id, root)
    df = df[df["fidelity_s"] == fidelity_s]
    if df.empty:
        raise DataUnavailable(f"{basket_id}: no {fidelity_s}s price history")
    wide = df.pivot_table(index="t", columns="leg", values="p", aggfunc="last").sort_index()
    wide.index = pd.to_datetime(wide.index, unit="s", utc=True)
    grid = pd.date_range(wide.index[0].ceil(f"{fidelity_s}s"), wide.index[-1].floor(f"{fidelity_s}s"),
                         freq=f"{fidelity_s}s")
    limit = max(int(pd.Timedelta(max_gap).total_seconds() // fidelity_s), 1)
    wide = wide.reindex(wide.index.union(grid)).ffill(limit=limit).reindex(grid)
    legs = [l.leg_id for l in basket.legs if l.leg_id in wide.columns]
    return wide[legs].dropna()


def _snap_down(x: float, tick: float) -> float:
    return math.floor(x / tick + 1e-9) * tick


def modelled_book(p: float, tick: float, spread_ticks: int, top_size: float, levels: int = 5
                  ) -> tuple[list[tuple[int, float]], list[tuple[int, float]]]:
    """Symmetric ladder around a price-history value: ``spread_ticks`` wide, ``levels`` deep,
    sizes growing linearly with distance from the top (a stylised Polymarket book)."""
    tick = 0.001 if (p < 0.04 or p > 0.96) else tick
    half = spread_ticks * tick / 2
    bid = max(_snap_down(p - half + 1e-12, tick), 0.0)
    ask = min(bid + spread_ticks * tick, 1.0)
    if bid <= 0:
        bid = math.nan
    bids, asks = [], []
    for k in range(levels):
        size = top_size * (1 + k)
        if math.isfinite(bid) and bid - k * tick > 0:
            bids.append((px_to_int(round(bid - k * tick, 6)), size))
        if ask + k * tick < 1:
            asks.append((px_to_int(round(ask + k * tick, 6)), size))
    return bids, asks


def book_calibration(basket: Basket, tob: pd.DataFrame | None) -> dict[str, tuple[int, float]]:
    """Per-leg (median spread in ticks, median top size) from recorded books, else (1, 500)."""
    out: dict[str, tuple[int, float]] = {}
    for leg in basket.legs:
        spread_ticks, size = 1, 500.0
        if tob is not None and len(tob):
            g = tob[(tob["leg"] == leg.leg_id) & tob["clean"]].dropna(subset=["bid", "ask"])
            if len(g):
                tick = leg.tick_size
                spread_ticks = max(int(round(float(((g["ask"] - g["bid"]) / tick).median()))), 1)
                size = float(np.nanmedian(np.r_[g["bid_sz"].to_numpy(), g["ask_sz"].to_numpy()]))
        out[leg.leg_id] = (min(spread_ticks, 10), max(size, 5.0))
    return out


def load_real_prices(basket_id: str, *, fidelity_s: int = 60, root: Path = PRICES_ROOT,
                     cfg: MarketsConfig | None = None, calibrate_from_books: bool = True) -> Dataset:
    cfg = cfg or load_markets()
    basket = get_basket(basket_id, cfg)
    wide = prices_grid(basket_id, fidelity_s=fidelity_s, root=root, cfg=cfg)
    tob_rec = None
    if calibrate_from_books:
        try:
            tob_rec = load_real_books(basket_id, cfg=cfg).top_of_book()
        except DataUnavailable:
            tob_rec = None
    calib = book_calibration(basket, tob_rec)
    with open(Path(root) / basket_id / "manifest.json", encoding="utf-8") as fh:
        man = json.load(fh)
    hours = (wide.index[-1] - wide.index[0]).total_seconds() / 3600 if len(wide) else 0.0
    info = DatasetInfo(DataKind.REAL_PRICES, basket_id, basket.title,
                       wide.index[0].isoformat()[:19] if len(wide) else None,
                       wide.index[-1].isoformat()[:19] if len(wide) else None, hours, len(wide), 1,
                       [{"manifest": str(Path(root) / basket_id / "manifest.json"), "fetched_at": man.get("fetched_at")}])
    info.notes.append("Execution books are MODELLED: per-leg spread "
                      + ", ".join(f"{k}={v[0]} tick(s)" for k, v in calib.items())
                      + (" (medians of the recorded live books)." if tob_rec is not None else " (default 1 tick)."))
    leg_by_id = {l.leg_id: l for l in basket.legs}
    t_ns = wide.index.asi8
    values = wide.to_numpy(float)
    cols = list(wide.columns)

    def frames() -> Iterator[tuple[int, list[Event]]]:
        yield int(t_ns[0]) if len(t_ns) else 0, [MetaEvent("replay_start", {"session_id": "prices"}, int(t_ns[0]) if len(t_ns) else 0)]
        prev = [math.nan] * len(cols)
        for i, t in enumerate(t_ns):
            evs: list[Event] = []
            for j, leg_id in enumerate(cols):
                p = values[i, j]
                if p == prev[j]:
                    continue
                prev[j] = p
                leg = leg_by_id[leg_id]
                st, sz = calib[leg_id]
                bids, asks = modelled_book(p, leg.tick_size, st, sz)
                evs.append(BookEvent(leg.yes_token_id, leg.condition_id, bids, asks, int(t // 1_000_000), int(t),
                                     source="modelled"))
            if evs:
                yield int(t), evs

    def tob() -> pd.DataFrame:
        rows = []
        for j, leg_id in enumerate(cols):
            leg = leg_by_id[leg_id]
            st, sz = calib[leg_id]
            for t, p in zip(t_ns, values[:, j]):
                bids, asks = modelled_book(p, leg.tick_size, st, sz, levels=1)
                rows.append((int(t), leg_id, bids[0][0] / 1e6 if bids else math.nan,
                             asks[0][0] / 1e6 if asks else math.nan, sz, sz, True))
        return pd.DataFrame(rows, columns=["t_ns", "leg", "bid", "ask", "bid_sz", "ask_sz", "clean"])

    return Dataset(info, basket, frames, tob)


# --------------------------------------------------------------------------- synthetic
def load_synthetic(basket_id: str = "SYNTHETIC_demo5", *, cfg: MarketsConfig | None = None,
                   duration_s: float | None = None) -> Dataset:
    from .clob_client import parse_message
    from .synthetic import SyntheticParams, iter_wire_messages, synthetic_basket, synthetic_tob

    cfg = cfg or load_markets()
    if basket_id not in cfg.synthetic_baskets:
        raise DataUnavailable(f"{basket_id} is not a configured synthetic basket")
    entry = dict(cfg.synthetic_baskets[basket_id])
    params = dict(entry.get("params", {}))
    if duration_s is not None:
        params["duration_s"] = duration_s
    p = SyntheticParams.from_dict(params, name=basket_id, seed=entry.get("seed"))
    basket = synthetic_basket(p)
    tob = synthetic_tob(p)
    info = DatasetInfo(DataKind.SYNTHETIC, basket_id, basket.title, _iso(tob["t_ns"].min()), _iso(tob["t_ns"].max()),
                       p.duration_s / 3600, len(tob), 1, [{"generator": "src.synthetic", "params": p.to_dict()}],
                       seed=p.seed)

    def frames() -> Iterator[tuple[int, list[Event]]]:
        first = True
        for t, msg in iter_wire_messages(p):
            if first:
                yield t, [MetaEvent("replay_start", {"session_id": "synthetic"}, t)]
                first = False
            evs = parse_message(msg, t)
            if evs:
                yield t, evs

    return Dataset(info, basket, frames, lambda: tob)


# --------------------------------------------------------------------------- dispatcher
_ORDER = (DataKind.REAL_BOOKS, DataKind.REAL_PRICES, DataKind.SYNTHETIC)


def load_dataset(basket_id: str, *, prefer: Sequence[DataKind | str] = _ORDER, mode: str | None = None,
                 cfg: MarketsConfig | None = None, synthetic_fallback: str = "SYNTHETIC_demo5",
                 min_book_hours: float = 0.0) -> Dataset:
    """Load the first available kind in ``prefer`` order (env ``BAYES_DATA_MODE`` overrides)."""
    cfg = cfg or load_markets()
    mode = (mode or os.environ.get("BAYES_DATA_MODE") or "auto").lower()
    if mode == "real":
        prefer = (DataKind.REAL_BOOKS, DataKind.REAL_PRICES)
    elif mode in ("real_books", "real_prices", "synthetic"):
        prefer = (DataKind(mode),)
    tried = []
    for kind in (DataKind(k) for k in prefer):
        try:
            if kind == DataKind.REAL_BOOKS:
                return load_real_books(basket_id, cfg=cfg, min_hours=min_book_hours)
            if kind == DataKind.REAL_PRICES:
                return load_real_prices(basket_id, cfg=cfg)
            sid = basket_id if basket_id in cfg.synthetic_baskets else synthetic_fallback
            ds = load_synthetic(sid, cfg=cfg)
            if sid != basket_id:
                ds.info.notes.append(f"FALLBACK: no real data for `{basket_id}` ({'; '.join(tried)}); "
                                     f"showing synthetic basket `{sid}` instead.")
                logger.warning("no real data for %s; falling back to %s", basket_id, sid)
            return ds
        except DataUnavailable as exc:
            tried.append(str(exc))
    raise DataUnavailable(f"{basket_id}: none of {[DataKind(k).value for k in prefer]} available: {tried}")


def resolution_events(basket: Basket, winner_leg_id: str, t_ns: int) -> list[Event]:
    """Helper for tests/what-ifs: the ``market_resolved`` events of a basket settling on one leg."""
    out: list[Event] = []
    for l in basket.legs:
        won = l.leg_id == winner_leg_id
        out.append(MarketResolvedEvent(l.condition_id, (l.yes_token_id, l.no_token_id),
                                       l.yes_token_id if won else l.no_token_id, "Yes" if won else "No",
                                       t_ns // 1_000_000, t_ns))
    return out
